repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - name: Verificando os arquivos YAML
        id: check-yaml
      - name: Verificando arquivos grandes
        id: check-added-large-files
      - name: Corrigindo o final do arquivo
        id: end-of-file-fixer
      - name: Removendo espaços em branco no final das linhas
        id: trailing-whitespace
      - name: Verificando conflitos de merge
        id: check-merge-conflict

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - name: Formatando arquivos Terraform
        id: terraform_fmt
        files: ^terraform/
      - name: Validando arquivos Terraform
        id: terraform_validate
        files: ^terraform/
      - name: Verificando erros de linting no Terraform
        id: terraform_tflint
        files: ^terraform/
      - name: Verificando vulnerabilidades no Terraform
        id: terraform_trivy
        files: ^terraform/
