name: Realizando o deploy da aplicação para os ambientes
on:
  push:
    # branches:
    #   - main
    paths:
      - .github/workflows/build.yaml
      - app/Dockerfile
      - app/src/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy-staging:
    name: Realizando o deploy para o ambiente de staging
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      RAILWAY_ENVIRONMENT: staging

  deploy-production:
    needs: deploy-staging
    name: Realizando o deploy para o ambiente de production
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      RAILWAY_ENVIRONMENT: production
