name: Run Robot Framework Testes
run-name: On Push - API Testing Run
on: [push]

jobs:
  api-tests:
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node.js 19.1
        uses: actions/setup-node@v3
        with:
          node-version: '19.1'

      - name: Install Requirements
        run: 
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-database
          pip install robotframework-requests
          rfbrowser init

      - name: Run RF API tests
        run: 
          robot -d ./results -v HEADLESS:true -v robot