name: Pipeline de Testes Unitários, Integração e Cobertura de Código
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/testes.yaml
      - app/src/**
env:
  JAVA_VERSION: 25
  JAVA_DISTRIBUTION: 'zulu'
  TARGET: target-artifact

jobs:
  unit-test:
    name: Executando testes unitários com JUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configuração do JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
          cache-dependency-path: ./app/pom.xml

      - name: Executar testes unitários e gerar cobertura
        working-directory: ./app
        run: mvn test jacoco:report -Dgroups=unit

  integration-test:
    name: Executando testes de integração com JUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configuração do JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
          cache-dependency-path: ./app/pom.xml

      - name: Executar testes de integração
        working-directory: ./app
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ticket_sales
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password
        run: mvn test -Dgroups=integration
  sonarqube:
    name: Executando análise de código com SonarQube
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configuração do JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        working-directory: ./app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=JvictorMarques_api-tickets-sale
